version: "3.9"
services:
  api:
    build: ./backend
    volumes: [ "./data:/data" ]
    depends_on: [ redis ]
    ports: [ "8000:8000" ]

  worker:
    build: ./backend
    command: celery -A backend.workers.celery worker --loglevel=INFO
    volumes: [ "./data:/data" ]
    depends_on: [ redis ]

  redis:
    image: redis:7

  web:
    build: ./frontend
    ports: [ "3000:80" ]
